# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51f976afd43a263e99ea5fa2eddfc649eeab78bce0947aecf82a6d1e6f5f05a3311c14a8f0bf07419b806c11b6c09ddac0035d909a4d8229690850b7482e747b

test:
  secret_key_base: 1dd6afaefe582d6cca2b72c9fc708f721a6756d6eab3a1f60a26631e5bc128c88b045dbfd2414040d42d7bcb1f8a13c555975b7615d6b8c2b2f56083002d7b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
